"""Initial baseline migration

Revision ID: 1c6b0c0f41f6
Revises: 
Create Date: 2026-02-23 08:10:28.442045

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1c6b0c0f41f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapter_crosswalks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('source_value', sa.String(), nullable=False),
    sa.Column('internal_id', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adapter_crosswalks_namespace'), 'adapter_crosswalks', ['namespace'], unique=False)
    op.create_index(op.f('ix_adapter_crosswalks_source_value'), 'adapter_crosswalks', ['source_value'], unique=False)
    op.create_table('adapter_inbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'MAPPED', 'FORWARDED', 'DLQ', 'ERROR', name='inbox_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adapter_inbox_source_system'), 'adapter_inbox', ['source_system'], unique=False)
    op.create_table('dead_letter_queue',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inbox_id', sa.Uuid(), nullable=False),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('error_reason', sa.String(), nullable=False),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kernel_commodity_registry',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_unit', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DEPRECATED', name='commodity_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_kernel_commodity_registry_code'), 'kernel_commodity_registry', ['code'], unique=False)
    op.create_table('kernel_node_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kernel_node_registry_parent_id'), 'kernel_node_registry', ['parent_id'], unique=False)
    op.create_index(op.f('ix_kernel_node_registry_uid'), 'kernel_node_registry', ['uid'], unique=False)
    op.create_table('kernel_system_policy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_key', sa.String(), nullable=False),
    sa.Column('applies_to_node', sa.String(), nullable=False),
    sa.Column('applies_to_item', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_key', 'applies_to_node', 'applies_to_item', name='uq_system_policy_key_coords')
    )
    op.create_index(op.f('ix_kernel_system_policy_applies_to_item'), 'kernel_system_policy', ['applies_to_item'], unique=False)
    op.create_index(op.f('ix_kernel_system_policy_applies_to_node'), 'kernel_system_policy', ['applies_to_node'], unique=False)
    op.create_index(op.f('ix_kernel_system_policy_policy_key'), 'kernel_system_policy', ['policy_key'], unique=False)
    op.create_table('ledger_approval_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('staged_command_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'REJECT', name='approval_action_type'), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_approval_audit_staged_command_id'), 'ledger_approval_audit', ['staged_command_id'], unique=False)
    op.create_table('ledger_idempotency_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'STAGED', 'COMPLETED', 'FAILED', name='idempotency_status'), nullable=False),
    sa.Column('version_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_idempotency_registry_source_event_id'), 'ledger_idempotency_registry', ['source_event_id'], unique=True)
    op.create_table('ledger_in_transit_registry',
    sa.Column('transfer_id', sa.Uuid(), nullable=False),
    sa.Column('source_node_id', sa.String(), nullable=False),
    sa.Column('dest_node_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('qty_shipped', sa.Integer(), nullable=False),
    sa.Column('qty_received', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PARTIAL', 'COMPLETED', 'STALE_AUTO_CLOSED', 'FAILED_AUTO_CLOSE', name='in_transit_status'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auto_close_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    op.create_index(op.f('ix_ledger_in_transit_registry_dest_node_id'), 'ledger_in_transit_registry', ['dest_node_id'], unique=False)
    op.create_index(op.f('ix_ledger_in_transit_registry_item_id'), 'ledger_in_transit_registry', ['item_id'], unique=False)
    op.create_index(op.f('ix_ledger_in_transit_registry_source_node_id'), 'ledger_in_transit_registry', ['source_node_id'], unique=False)
    op.create_table('ledger_internal_dlq',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_process', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_internal_dlq_reference_id'), 'ledger_internal_dlq', ['reference_id'], unique=False)
    op.create_table('ledger_inventory_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('running_balance', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_inventory_events_item_id'), 'ledger_inventory_events', ['item_id'], unique=False)
    op.create_index(op.f('ix_ledger_inventory_events_node_id'), 'ledger_inventory_events', ['node_id'], unique=False)
    op.create_index(op.f('ix_ledger_inventory_events_source_event_id'), 'ledger_inventory_events', ['source_event_id'], unique=False)
    op.create_table('ledger_staged_commands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=False),
    sa.Column('command_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('stage_reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('AWAITING', 'APPROVED', 'REJECTED', 'EXPIRED', name='staged_command_status'), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_staged_commands_node_id'), 'ledger_staged_commands', ['node_id'], unique=False)
    op.create_index(op.f('ix_ledger_staged_commands_source_event_id'), 'ledger_staged_commands', ['source_event_id'], unique=False)
    op.create_table('ledger_stock_balances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'item_id', name='uq_stock_balance_node_item')
    )
    op.create_index(op.f('ix_ledger_stock_balances_item_id'), 'ledger_stock_balances', ['item_id'], unique=False)
    op.create_index(op.f('ix_ledger_stock_balances_node_id'), 'ledger_stock_balances', ['node_id'], unique=False)
    op.create_table('mapping_contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dsl_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mapping_contracts')
    op.drop_index(op.f('ix_ledger_stock_balances_node_id'), table_name='ledger_stock_balances')
    op.drop_index(op.f('ix_ledger_stock_balances_item_id'), table_name='ledger_stock_balances')
    op.drop_table('ledger_stock_balances')
    op.drop_index(op.f('ix_ledger_staged_commands_source_event_id'), table_name='ledger_staged_commands')
    op.drop_index(op.f('ix_ledger_staged_commands_node_id'), table_name='ledger_staged_commands')
    op.drop_table('ledger_staged_commands')
    op.drop_index(op.f('ix_ledger_inventory_events_source_event_id'), table_name='ledger_inventory_events')
    op.drop_index(op.f('ix_ledger_inventory_events_node_id'), table_name='ledger_inventory_events')
    op.drop_index(op.f('ix_ledger_inventory_events_item_id'), table_name='ledger_inventory_events')
    op.drop_table('ledger_inventory_events')
    op.drop_index(op.f('ix_ledger_internal_dlq_reference_id'), table_name='ledger_internal_dlq')
    op.drop_table('ledger_internal_dlq')
    op.drop_index(op.f('ix_ledger_in_transit_registry_source_node_id'), table_name='ledger_in_transit_registry')
    op.drop_index(op.f('ix_ledger_in_transit_registry_item_id'), table_name='ledger_in_transit_registry')
    op.drop_index(op.f('ix_ledger_in_transit_registry_dest_node_id'), table_name='ledger_in_transit_registry')
    op.drop_table('ledger_in_transit_registry')
    op.drop_index(op.f('ix_ledger_idempotency_registry_source_event_id'), table_name='ledger_idempotency_registry')
    op.drop_table('ledger_idempotency_registry')
    op.drop_index(op.f('ix_ledger_approval_audit_staged_command_id'), table_name='ledger_approval_audit')
    op.drop_table('ledger_approval_audit')
    op.drop_index(op.f('ix_kernel_system_policy_policy_key'), table_name='kernel_system_policy')
    op.drop_index(op.f('ix_kernel_system_policy_applies_to_node'), table_name='kernel_system_policy')
    op.drop_index(op.f('ix_kernel_system_policy_applies_to_item'), table_name='kernel_system_policy')
    op.drop_table('kernel_system_policy')
    op.drop_index(op.f('ix_kernel_node_registry_uid'), table_name='kernel_node_registry')
    op.drop_index(op.f('ix_kernel_node_registry_parent_id'), table_name='kernel_node_registry')
    op.drop_table('kernel_node_registry')
    op.drop_index(op.f('ix_kernel_commodity_registry_code'), table_name='kernel_commodity_registry')
    op.drop_table('kernel_commodity_registry')
    op.drop_table('dead_letter_queue')
    op.drop_index(op.f('ix_adapter_inbox_source_system'), table_name='adapter_inbox')
    op.drop_table('adapter_inbox')
    op.drop_index(op.f('ix_adapter_crosswalks_source_value'), table_name='adapter_crosswalks')
    op.drop_index(op.f('ix_adapter_crosswalks_namespace'), table_name='adapter_crosswalks')
    op.drop_table('adapter_crosswalks')
    # ### end Alembic commands ###
