"""add_missing_inbox_columns

Revision ID: 20853e295cf6
Revises: 24c811d21401
Create Date: 2026-03-01 23:26:18.888160

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '20853e295cf6'
down_revision: Union[str, Sequence[str], None] = '24c811d21401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Manually added: Create contract_status enum type
    op.execute("CREATE TYPE contract_status AS ENUM ('DRAFT', 'REVIEW', 'APPROVED', 'ACTIVE', 'DEPRECATED', 'ARCHIVED', 'REJECTED')")

    op.create_table('adapter_egress_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inbox_id', sa.Uuid(), nullable=False),
    sa.Column('destination_url', sa.String(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_status', sa.String(), nullable=True),
    sa.Column('response_body', sa.String(), nullable=True),
    sa.Column('retry_count', sa.BigInteger(), nullable=True),
    sa.Column('delivery_time_ms', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adapter_egress_logs_inbox_id'), 'adapter_egress_logs', ['inbox_id'], unique=False)
    op.drop_table('adapter_logs')
    op.add_column('adapter_inbox', sa.Column('mapped_payload', sa.JSON(), nullable=True))
    op.add_column('mapping_contracts', sa.Column('sample_in', sa.JSON(), nullable=True))
    op.add_column('mapping_contracts', sa.Column('expected_out', sa.JSON(), nullable=True))
    op.add_column('mapping_contracts', sa.Column('test_result_metadata', sa.JSON(), nullable=True))
    op.alter_column('mapping_contracts', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('DRAFT', 'REVIEW', 'APPROVED', 'ACTIVE', 'DEPRECATED', 'ARCHIVED', 'REJECTED', name='contract_status'),
               existing_nullable=False,
               postgresql_using="status::contract_status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mapping_contracts', 'status',
               existing_type=sa.Enum('DRAFT', 'REVIEW', 'APPROVED', 'ACTIVE', 'DEPRECATED', 'ARCHIVED', 'REJECTED', name='contract_status'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('mapping_contracts', 'test_result_metadata')
    op.drop_column('mapping_contracts', 'expected_out')
    op.drop_column('mapping_contracts', 'sample_in')
    op.drop_column('adapter_inbox', 'mapped_payload')
    
    # Manually added: Drop contract_status enum type
    op.execute("DROP TYPE contract_status")
    op.create_table('adapter_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('inbox_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('destination_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('request_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('response_status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response_body', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('execution_time_ms', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('adapter_logs_pkey'))
    )
    op.drop_index(op.f('ix_adapter_egress_logs_inbox_id'), table_name='adapter_egress_logs')
    op.drop_table('adapter_egress_logs')
    # ### end Alembic commands ###
