"""add processing to inbox_status

Revision ID: 2b989713eb9e
Revises: 4b8d4b3d707c
Create Date: 2026-02-25 02:51:23.998300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b989713eb9e'
down_revision: Union[str, Sequence[str], None] = '4b8d4b3d707c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Disable autocommit block for ALTER TYPE
    op.execute("COMMIT")
    op.execute("ALTER TYPE inbox_status ADD VALUE IF NOT EXISTS 'PROCESSING'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
