"""Add AdapterInbox tracking and AdapterLogs

Revision ID: 4b8d4b3d707c
Revises: 1c6b0c0f41f6
Create Date: 2026-02-23 23:53:28.825322

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4b8d4b3d707c'
down_revision: Union[str, Sequence[str], None] = '1c6b0c0f41f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapter_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inbox_id', sa.Uuid(), nullable=False),
    sa.Column('destination_url', sa.String(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_status', sa.String(), nullable=True),
    sa.Column('response_body', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adapter_logs_inbox_id'), 'adapter_logs', ['inbox_id'], unique=False)
    op.add_column('adapter_inbox', sa.Column('mapping_id', sa.String(), nullable=True))
    op.add_column('adapter_inbox', sa.Column('mapping_version', sa.String(), nullable=True))
    op.add_column('adapter_inbox', sa.Column('source_event_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_adapter_inbox_source_event_id'), 'adapter_inbox', ['source_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adapter_inbox_source_event_id'), table_name='adapter_inbox')
    op.drop_column('adapter_inbox', 'source_event_id')
    op.drop_column('adapter_inbox', 'mapping_version')
    op.drop_column('adapter_inbox', 'mapping_id')
    op.drop_index(op.f('ix_adapter_logs_inbox_id'), table_name='adapter_logs')
    op.drop_table('adapter_logs')
    # ### end Alembic commands ###
