"""init

Revision ID: 77bdfdeb57f8
Revises: 
Create Date: 2026-03-04 07:31:07.270142

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '77bdfdeb57f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapter_admin_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_by', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adapter_crosswalks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('namespace', sa.String(), nullable=False),
    sa.Column('source_value', sa.String(), nullable=False),
    sa.Column('internal_id', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('namespace', 'source_value', name='uq_crosswalk_namespace_source')
    )
    op.create_index(op.f('ix_adapter_crosswalks_namespace'), 'adapter_crosswalks', ['namespace'], unique=False)
    op.create_index(op.f('ix_adapter_crosswalks_source_value'), 'adapter_crosswalks', ['source_value'], unique=False)
    op.create_table('adapter_egress_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inbox_id', sa.Uuid(), nullable=False),
    sa.Column('contract_version_id', sa.String(), nullable=True),
    sa.Column('destination_url', sa.String(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('destination_http_code', sa.Integer(), nullable=True),
    sa.Column('destination_response', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adapter_egress_logs_inbox_id'), 'adapter_egress_logs', ['inbox_id'], unique=False)
    op.create_table('adapter_inbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('parent_inbox_id', sa.Uuid(), nullable=True),
    sa.Column('source_system', sa.String(), nullable=False),
    sa.Column('mapping_id', sa.String(), nullable=True),
    sa.Column('mapping_version', sa.String(), nullable=True),
    sa.Column('source_event_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('mapped_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSING', 'MAPPED', 'FORWARDED', 'RETRY_EGRESS', 'DLQ', 'DESTINATION_REJECTED', 'REPROCESSED', name='inbox_status'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("(status NOT IN ('MAPPED', 'FORWARDED', 'RETRY_EGRESS', 'DESTINATION_REJECTED')) OR (mapping_id IS NOT NULL AND mapping_version IS NOT NULL AND mapped_payload IS NOT NULL)", name='chk_mapped_state_requirements'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inbox_pending', 'adapter_inbox', ['status'], unique=False, postgresql_where=sa.text("status IN ('RECEIVED', 'MAPPED', 'RETRY_EGRESS')"))
    op.create_index(op.f('ix_adapter_inbox_correlation_id'), 'adapter_inbox', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_adapter_inbox_parent_inbox_id'), 'adapter_inbox', ['parent_inbox_id'], unique=False)
    op.create_index(op.f('ix_adapter_inbox_source_event_id'), 'adapter_inbox', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_adapter_inbox_source_system'), 'adapter_inbox', ['source_system'], unique=False)
    op.create_table('kernel_commodity_registry',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_unit', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DEPRECATED', name='commodity_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_kernel_commodity_registry_code'), 'kernel_commodity_registry', ['code'], unique=False)
    op.create_table('kernel_node_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kernel_node_registry_parent_id'), 'kernel_node_registry', ['parent_id'], unique=False)
    op.create_index(op.f('ix_kernel_node_registry_uid'), 'kernel_node_registry', ['uid'], unique=False)
    op.create_table('kernel_system_policy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_key', sa.String(), nullable=False),
    sa.Column('applies_to_node', sa.String(), nullable=True),
    sa.Column('applies_to_item', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kernel_system_policy_applies_to_item'), 'kernel_system_policy', ['applies_to_item'], unique=False)
    op.create_index(op.f('ix_kernel_system_policy_applies_to_node'), 'kernel_system_policy', ['applies_to_node'], unique=False)
    op.create_index(op.f('ix_kernel_system_policy_policy_key'), 'kernel_system_policy', ['policy_key'], unique=False)
    op.create_index('uq_system_policy_key_coords', 'kernel_system_policy', ['policy_key', sa.literal_column("COALESCE(applies_to_node, '__NULL__')"), sa.literal_column("COALESCE(applies_to_item, '__NULL__')")], unique=True)
    op.create_table('ledger_approval_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('staged_command_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'REJECT', name='approval_action_type'), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_approval_audit_staged_command_id'), 'ledger_approval_audit', ['staged_command_id'], unique=False)
    op.create_table('ledger_idempotency_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PROCESSING', 'STAGED', 'COMPLETED', 'FAILED', name='idempotency_status'), nullable=False),
    sa.Column('version_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_idempotency_registry_source_event_id'), 'ledger_idempotency_registry', ['source_event_id'], unique=True)
    op.create_table('ledger_in_transit_registry',
    sa.Column('transfer_id', sa.Uuid(), nullable=False),
    sa.Column('source_node_id', sa.String(), nullable=False),
    sa.Column('dest_node_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('qty_shipped', sa.BigInteger(), nullable=False),
    sa.Column('qty_received', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PARTIAL', 'COMPLETED', 'STALE_AUTO_CLOSED', 'FAILED_AUTO_CLOSE', 'LOST_IN_TRANSIT', name='in_transit_status'), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auto_close_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    op.create_index(op.f('ix_ledger_in_transit_registry_dest_node_id'), 'ledger_in_transit_registry', ['dest_node_id'], unique=False)
    op.create_index(op.f('ix_ledger_in_transit_registry_item_id'), 'ledger_in_transit_registry', ['item_id'], unique=False)
    op.create_index(op.f('ix_ledger_in_transit_registry_source_node_id'), 'ledger_in_transit_registry', ['source_node_id'], unique=False)
    op.create_table('ledger_internal_dlq',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_process', sa.String(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_internal_dlq_reference_id'), 'ledger_internal_dlq', ['reference_id'], unique=False)
    op.create_table('ledger_inventory_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('running_balance', sa.BigInteger(), nullable=False),
    sa.Column('adjustment_reason', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_inventory_events_item_id'), 'ledger_inventory_events', ['item_id'], unique=False)
    op.create_index(op.f('ix_ledger_inventory_events_node_id'), 'ledger_inventory_events', ['node_id'], unique=False)
    op.create_index(op.f('ix_ledger_inventory_events_source_event_id'), 'ledger_inventory_events', ['source_event_id'], unique=False)
    op.create_table('ledger_staged_commands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_event_id', sa.String(), nullable=False),
    sa.Column('command_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('stage_reason', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('AWAITING', 'APPROVED', 'REJECTED', 'EXPIRED', name='staged_command_status'), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_staged_commands_node_id'), 'ledger_staged_commands', ['node_id'], unique=False)
    op.create_index(op.f('ix_ledger_staged_commands_source_event_id'), 'ledger_staged_commands', ['source_event_id'], unique=False)
    op.create_table('ledger_stock_balances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'item_id', name='uq_stock_balance_node_item')
    )
    op.create_index(op.f('ix_ledger_stock_balances_item_id'), 'ledger_stock_balances', ['item_id'], unique=False)
    op.create_index(op.f('ix_ledger_stock_balances_node_id'), 'ledger_stock_balances', ['node_id'], unique=False)
    op.create_table('mapping_contracts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'APPROVED', 'ACTIVE', 'DEPRECATED', 'REJECTED', name='contract_status'), nullable=False),
    sa.Column('visible_in_ui', sa.Boolean(), nullable=False),
    sa.Column('dsl_config', sa.JSON(), nullable=False),
    sa.Column('sample_in', sa.JSON(), nullable=True),
    sa.Column('expected_out', sa.JSON(), nullable=True),
    sa.Column('test_result_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_table('commodity_packages',
    sa.Column('package_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('uom_name', sa.String(), nullable=False),
    sa.Column('base_unit_multiplier', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['kernel_commodity_registry.item_id'], ),
    sa.PrimaryKeyConstraint('package_id')
    )
    op.create_index(op.f('ix_commodity_packages_item_id'), 'commodity_packages', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commodity_packages_item_id'), table_name='commodity_packages')
    op.drop_table('commodity_packages')
    op.drop_table('mapping_contracts')
    op.drop_index(op.f('ix_ledger_stock_balances_node_id'), table_name='ledger_stock_balances')
    op.drop_index(op.f('ix_ledger_stock_balances_item_id'), table_name='ledger_stock_balances')
    op.drop_table('ledger_stock_balances')
    op.drop_index(op.f('ix_ledger_staged_commands_source_event_id'), table_name='ledger_staged_commands')
    op.drop_index(op.f('ix_ledger_staged_commands_node_id'), table_name='ledger_staged_commands')
    op.drop_table('ledger_staged_commands')
    op.drop_index(op.f('ix_ledger_inventory_events_source_event_id'), table_name='ledger_inventory_events')
    op.drop_index(op.f('ix_ledger_inventory_events_node_id'), table_name='ledger_inventory_events')
    op.drop_index(op.f('ix_ledger_inventory_events_item_id'), table_name='ledger_inventory_events')
    op.drop_table('ledger_inventory_events')
    op.drop_index(op.f('ix_ledger_internal_dlq_reference_id'), table_name='ledger_internal_dlq')
    op.drop_table('ledger_internal_dlq')
    op.drop_index(op.f('ix_ledger_in_transit_registry_source_node_id'), table_name='ledger_in_transit_registry')
    op.drop_index(op.f('ix_ledger_in_transit_registry_item_id'), table_name='ledger_in_transit_registry')
    op.drop_index(op.f('ix_ledger_in_transit_registry_dest_node_id'), table_name='ledger_in_transit_registry')
    op.drop_table('ledger_in_transit_registry')
    op.drop_index(op.f('ix_ledger_idempotency_registry_source_event_id'), table_name='ledger_idempotency_registry')
    op.drop_table('ledger_idempotency_registry')
    op.drop_index(op.f('ix_ledger_approval_audit_staged_command_id'), table_name='ledger_approval_audit')
    op.drop_table('ledger_approval_audit')
    op.drop_index('uq_system_policy_key_coords', table_name='kernel_system_policy')
    op.drop_index(op.f('ix_kernel_system_policy_policy_key'), table_name='kernel_system_policy')
    op.drop_index(op.f('ix_kernel_system_policy_applies_to_node'), table_name='kernel_system_policy')
    op.drop_index(op.f('ix_kernel_system_policy_applies_to_item'), table_name='kernel_system_policy')
    op.drop_table('kernel_system_policy')
    op.drop_index(op.f('ix_kernel_node_registry_uid'), table_name='kernel_node_registry')
    op.drop_index(op.f('ix_kernel_node_registry_parent_id'), table_name='kernel_node_registry')
    op.drop_table('kernel_node_registry')
    op.drop_index(op.f('ix_kernel_commodity_registry_code'), table_name='kernel_commodity_registry')
    op.drop_table('kernel_commodity_registry')
    op.drop_index(op.f('ix_adapter_inbox_source_system'), table_name='adapter_inbox')
    op.drop_index(op.f('ix_adapter_inbox_source_event_id'), table_name='adapter_inbox')
    op.drop_index(op.f('ix_adapter_inbox_parent_inbox_id'), table_name='adapter_inbox')
    op.drop_index(op.f('ix_adapter_inbox_correlation_id'), table_name='adapter_inbox')
    op.drop_index('idx_inbox_pending', table_name='adapter_inbox', postgresql_where=sa.text("status IN ('RECEIVED', 'MAPPED', 'RETRY_EGRESS')"))
    op.drop_table('adapter_inbox')
    op.drop_index(op.f('ix_adapter_egress_logs_inbox_id'), table_name='adapter_egress_logs')
    op.drop_table('adapter_egress_logs')
    op.drop_index(op.f('ix_adapter_crosswalks_source_value'), table_name='adapter_crosswalks')
    op.drop_index(op.f('ix_adapter_crosswalks_namespace'), table_name='adapter_crosswalks')
    op.drop_table('adapter_crosswalks')
    op.drop_table('adapter_admin_jobs')
    # ### end Alembic commands ###
