"""consolidate_dlq_into_inbox

Revision ID: ad545822c140
Revises: 2b989713eb9e
Create Date: 2026-02-26 04:18:29.268289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad545822c140'
down_revision: Union[str, Sequence[str], None] = '2b989713eb9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE inbox_status ADD VALUE IF NOT EXISTS 'RETRY'")
        op.execute("ALTER TYPE inbox_status ADD VALUE IF NOT EXISTS 'DLQ'")
        op.execute("ALTER TYPE inbox_status ADD VALUE IF NOT EXISTS 'ERROR'")
        op.execute("ALTER TYPE inbox_status ADD VALUE IF NOT EXISTS 'REPROCESSED'")
    
    op.drop_table('dead_letter_queue')
    op.add_column('adapter_inbox', sa.Column('correlation_id', sa.Uuid(), nullable=True))
    op.add_column('adapter_inbox', sa.Column('parent_inbox_id', sa.Uuid(), nullable=True))
    op.add_column('adapter_inbox', sa.Column('error_message', sa.String(), nullable=True))
    op.create_index('idx_inbox_pending', 'adapter_inbox', ['status'], unique=False, postgresql_where=sa.text("status IN ('RECEIVED', 'RETRY')"))
    op.create_index(op.f('ix_adapter_inbox_correlation_id'), 'adapter_inbox', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_adapter_inbox_parent_inbox_id'), 'adapter_inbox', ['parent_inbox_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adapter_inbox_parent_inbox_id'), table_name='adapter_inbox')
    op.drop_index(op.f('ix_adapter_inbox_correlation_id'), table_name='adapter_inbox')
    op.drop_index('idx_inbox_pending', table_name='adapter_inbox', postgresql_where=sa.text("status IN ('RECEIVED', 'RETRY')"))
    op.drop_column('adapter_inbox', 'error_message')
    op.drop_column('adapter_inbox', 'parent_inbox_id')
    op.drop_column('adapter_inbox', 'correlation_id')
    op.create_table('dead_letter_queue',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('inbox_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_system', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error_reason', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('context_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('dead_letter_queue_pkey'))
    )
    # ### end Alembic commands ###
